<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class FormPageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function merge(array $input)
    {
        return parent::merge($input); // TODO: Change the autogenerated stub
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'link'      => 'required|regex:/((https:\/\/)([a-z.0-9]+)\.([a-z]+))/',
            'limit'     => 'nullable',
            'lifetime'  => 'required|numeric|between:1,24'
        ];
    }
}
